name: Build + Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_lint:
    name: Build + Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --cwd example --frozen-lockfile
          yarn install --frozen-lockfile

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typescript

      - name: Build package
        run: yarn prepare
